meal_plans/urls.py
from django.urls import path

from meal_plans.views import (
    MealPlanListView,
    MealPlanDetailView,
    MealPlanCreateView,
    MealPlanUpdateView,
    MealPlanDeleteView,
)

urlpatterns = [
    path("", MealPlanListView.as_view(), name="meal_plan_list"),
    path("<int:pk>/", MealPlanDetailView.as_view(), name="meal_plan_detail"),
    path("new/", MealPlanCreateView.as_view(), name="meal_plan_new"),
    path("<int:pk>/edit/", MealPlanUpdateView.as_view(), name="meal_plan_edit"),
    path("<int:pk>/delete/", MealPlanDeleteView.as_view(), name="meal_plan_delete"),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls"), name="recipes"),
    path("tags/", include("tags.urls"), name ="tags"),
    path("mealplans/", include("meal_plans.urls"), name="meal_plans"),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDeleteView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

meal_plans/models.py
from django.db import models


from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


# Create your models here.


class MealPlan(models.Model):
    plan_name = models.CharField(max_length=120)
    date_served = models.DateField()
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="meal_plan",
        on_delete=models.CASCADE,
        null=True,
    )
    recipes = models.ManyToManyField("recipes.Recipe", related_name="mealplan")

    def __str__(self):
        return self.plan_name + " meal plan on " + str(self.date_served)

meal_plans/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from meal_plans.models import MealPlan

# List View
class MealPlanListView(LoginRequiredMixin, ListView):
    model = MealPlan
    template_name = "plans/list.html"
    paginate_by = 5

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


# Detail View
class MealPlanDetailView(LoginRequiredMixin, DetailView):
    model = MealPlan
    template_name = "plans/detail.html"

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


# Create View - edit
# add save for m2m relationships
class MealPlanCreateView(LoginRequiredMixin, CreateView):
    model = MealPlan
    template_name = "plans/new.html"
    fields = ["plan_name", "date_served", "recipes"]

    def form_valid(self, form):
        plan = form.save(commit=False)
        plan.owner = self.request.user
        plan.save()
        form.save_m2m()
        return redirect("meal_plan_detail", pk=plan.id)


# Update View - edit
class MealPlanUpdateView(LoginRequiredMixin, UpdateView):
    model = MealPlan
    template_name = "plans/edit.html"
    fields = ["plan_name", "date_served", "recipes"]

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

    def get_success_url(self) -> str:
        return reverse_lazy("meal_plan_detail", args=[self.object.id])


# Delete View - edit
class MealPlanDeleteView(LoginRequiredMixin, DeleteView):
    model = MealPlan
    template_name = "plans/delete.html"
    success_url = reverse_lazy("meal_plan_list")

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

meal_plans/templates/plans/delete.html
{% extends 'base.html' %}

{% block content%}
  <main>
    <div class="delete-form">
      <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ mealplan }}"?</p>
        {{ form.as_p }}
        <div>
          <button class="button">Delete</button>
        </div>
      </form>
    </div>
  </main>
{% endblock content%}

meal_plans/templates/plans/detail.html
{% extends 'base.html' %}
{% load markdownify %}

{% comment %} {% block content%}
  <main class="recipe-grid">
      <div class="recipe-card">
        <h2 class="recipe-card-title">
          <a href="{% url 'meal_plan_detail' mealplan.pk %}">{{ mealplan.plan_name }}</a>
        </h2>
        <p >{{ mealplan.owner }}</p>
      </div>
  </main>
{% endblock content%}
{% extends 'base.html' %}
{% load markdownify %} {% endcomment %}


{% block content%}
<main class="recipe-detail">
    <div>
        <a href="{% url 'meal_plan_edit' mealplan.id %}">Edit</a>
        <a href="{% url 'meal_plan_delete' mealplan.id %}">Delete</a>
    </div>
    <h1>Recipes for {{ mealplan.plan_name }}</h1>
    <h2>on {{ mealplan.date_served }}</h2>
    <ol>
        {% for recipe in mealplan.recipes.all %}
            <p><a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a></p>
        {% endfor %}
    </ol>
</main>
{% endblock content%}

meal_plans/templates/plans/edit.html
{% extends 'base.html' %}

{% block content %}
  <main class="recipe-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Update</button>
      </div>
    </form>
  </main>
{% endblock content %}

meal_plans/templates/plans/list.html
{% extends "base.html" %}

{% block pagination %}
    <div class="pagination">
      <span class="step-links">
        {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>


        {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
      </span>
    </div>
  </header>
{% endblock pagination %}

{% block content %}
<h2><a href="{% url 'meal_plan_new' %}">Create new meal plan</a></h2>
<main class="recipe-grid">
    {% for mealplan in mealplan_list %}
      <div class="recipe-card">
        <h2 class="recipe-card-title">
          <a href="{% url 'meal_plan_detail' mealplan.pk %}">{{ mealplan.plan_name }}</a>
        </h2>
        <p >{{ mealplan.date_served }}</p>
      </div>
    {% endfor %}
  </main>
{% endblock content %}

meal_plans/templates/plans/new.html
{% extends 'base.html' %}

{% block content %}
  <main class="recipe-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Create</button>
      </div>
    </form>
  </main>
{% endblock %}